// Extracting Strings for Translating
var gettext = function(s) {
    return s;
};

angular.module('enplug.sdk.utils').constant('states', [
    { name: gettext('Alabama'), code: 'AL' },
    { name: gettext('Alaska'), code: 'AK' },
    { name: gettext('Arizona'), code: 'AZ' },
    { name: gettext('Arkansas'), code: 'AR' },
    { name: gettext('California'), code: 'CA' },
    { name: gettext('Colorado'), code: 'CO' },
    { name: gettext('Connecticut'), code: 'CT' },
    { name: gettext('Delaware'), code: 'DE' },
    { name: gettext('District of Columbia'), code: 'DC' },
    { name: gettext('Florida'), code: 'FL' },
    { name: gettext('Georgia'), code: 'GA' },
    { name: gettext('Hawaii'), code: 'HI' },
    { name: gettext('Idaho'), code: 'ID' },
    { name: gettext('Illinois'), code: 'IL' },
    { name: gettext('Indiana'), code: 'IN' },
    { name: gettext('Iowa'), code: 'IA' },
    { name: gettext('Kansa'), code: 'KS' },
    { name: gettext('Kentucky'), code: 'KY' },
    { name: gettext('Lousiana'), code: 'LA' },
    { name: gettext('Maine'), code: 'ME' },
    { name: gettext('Maryland'), code: 'MD' },
    { name: gettext('Massachusetts'), code: 'MA' },
    { name: gettext('Michigan'), code: 'MI' },
    { name: gettext('Minnesota'), code: 'MN' },
    { name: gettext('Mississippi'), code: 'MS' },
    { name: gettext('Missouri'), code: 'MO' },
    { name: gettext('Montana'), code: 'MT' },
    { name: gettext('Nebraska'), code: 'NE' },
    { name: gettext('Nevada'), code: 'NV' },
    { name: gettext('New Hampshire'), code: 'NH' },
    { name: gettext('New Jersey'), code: 'NJ' },
    { name: gettext('New Mexico'), code: 'NM' },
    { name: gettext('New York'), code: 'NY' },
    { name: gettext('North Carolina'), code: 'NC' },
    { name: gettext('North Dakota'), code: 'ND' },
    { name: gettext('Ohio'), code: 'OH' },
    { name: gettext('Oklahoma'), code: 'OK' },
    { name: gettext('Oregon'), code: 'OR' },
    { name: gettext('Pennsylvania'), code: 'PA' },
    { name: gettext('Rhode Island'), code: 'RI' },
    { name: gettext('South Carolina'), code: 'SC' },
    { name: gettext('South Dakota'), code: 'SD' },
    { name: gettext('Tennessee'), code: 'TN' },
    { name: gettext('Texas'), code: 'TX' },
    { name: gettext('Utah'), code: 'UT' },
    { name: gettext('Vermont'), code: 'VT' },
    { name: gettext('Virginia'), code: 'VA' },
    { name: gettext('Washington'), code: 'WA' },
    { name: gettext('West Virginia'), code: 'WV' },
    { name: gettext('Wisconsin'), code: 'WI' },
    { name: gettext('Wyoming'), code: 'WY' }
]);
