angular.module('enplug.sdk.utils').constant('timezone', [
    "(UTC-10:00) Hawaii",
    "(UTC-09:00) Alaska",
    "(UTC-08:00) Pacific Time (US & Canada)",
    "(UTC-07:00) Arizona",
    "(UTC-07:00) Mountain Time (US & Canada)",
    "(UTC-06:00) Central Time (US & Canada)",
    "(UTC-05:00) Eastern Time (US & Canada)",
    "(UTC-05:00) Bogota, Lima, Quito, Rio Branco",
    "(UTC-05:00) Indiana (East)",
    "(UTC-03:00) Brasilia",
    "(UTC) Dublin, Edinburgh, Lisbon, London",
    "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
    "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    "(UTC+02:00) Athens, Bucharest",
    "(UTC+04:00) Moscow, St. Petersburg, Volgograd",
    "(UTC+08:00) Kuala Lumpur, Singapore",
    "(UTC+08:00) Perth",
    "(UTC+09:00) Osaka, Sapporo, Tokyo",
    "(UTC+09:30) Adelaide",
    "(UTC+10:00) Guam, Port Moresby",
    "(UTC+10:00) Brisbane",
    "(UTC+12:00) Auckland, Wellington"
]);
